### ISSUE TITLE
Can you provide a PDF of the schematic please

### ISSUE THREAD

**Issue by rolandking** [aaronw2/T-962-Temp-Fan#1]
Looks like a nice project - thanks very much for sharing it. 

Attempting to load up in kicad I have version mismatches and library issues which I suspect might not be that uncommon (I'm still on kicad 4.x). You provide the gerbers which is great, can you PDF up the schematic and upload that too please so people without kicad, or without a compatible version of kicad, can read, understand and build the project. 

Thanks very much.

**Comment by aaronw2** [comment]
Done. Note that my gerbers may have been out of date and I may have screwed up on the minimum solder mask width. Anyway, all should be good now and I also included a PDF of the schematic. This was done using KiCad 5.0.2 and I have my own libraries for some of these parts.

All parts can be found on Digikey, though the MAX31850s are a lot cheaper from Mouser.
